### Create account
POST http://localhost:8080/account/create
Content-Type: application/json

{"email": "user@example.com"}

###

### Get balance (use the id returned from create)
GET http://localhost:8080/account/1/balance

###

### Deposit
POST http://localhost:8080/account/1/deposit
Content-Type: application/json

{"amount": 500.00}

###

### Withdraw
POST http://localhost:8080/account/1/withdraw
Content-Type: application/json

{"amount": 100.00}

###

### Transaction history
GET http://localhost:8080/account/1/history

###
